apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: project1
  labels:
    app: webapp
spec:
  replicas: 1
  revisionHistoryLimit: 2  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: webapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        # resources:
        #   requests:
        #     memory: "200Mi"
        #     cpu: "500m"
        #   limits:
        #     memory: "200Mi"
        #     cpu: "1000m"
        env:
        - name: VUE_APP_API_URL
          value: "http://127.0.0.1:8081"
        - name: VUE_APP_FIREBASE_API_KEY
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: vue-app-firebase-api-key
        - name: VUE_APP_FIREBASE_AUTH_DOMAIN
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: vue-app-firebase-auth-domain
        - name: VUE_APP_FIREBASE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: vue-app-firebase-project-id
        - name: VUE_APP_FIREBASE_STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: vue-app-firebase-storage-bucket
        - name: VUE_APP_FIREBASE_MESSAGING_SENDER_ID
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: vue-app-firebase-messaging-sender-id
        - name: VUE_APP_FIREBASE_APP_ID
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: vue-app-firebase-app-id
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: project1
spec:
  selector:
    app: webapp
  type: LoadBalancer
  ports:
    - name: webapp-service
      port: 8080
      targetPort: 8080
      protocol: TCP